/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function compile(sourceCode: string, fileName: string): string
export function compile(sourceCode: string, fileName: string): string
export function compile(sourceCode: string, fileName: string): string
export interface CompileOptions {
  conditions: Array<string>
  extensions: Array<string>
  cwd: string
}
export function compile(sourceCode: string, fileName: string, options: CompileOptions): string
export interface CompileOptions {
  conditions: Array<string>
  extensions: Array<string>
  cwd: string
}
export function compile(sourceCode: string, fileName: string, options: CompileOptions): string
export interface CompileOptions {
  conditions: Array<string>
  extensions: Array<string>
  cwd: string
}
export function compile(sourceCode: string, fileName: string, options: CompileOptions): string
export interface CompileOptions {
  conditions: Array<string>
  extensions: Array<string>
  cwd: string
}
export function compile(sourceCode: string, fileName: string, options: CompileOptions): string
