export const ProcessEnvKeys = {
  CLICoverage: 'XBELL_CLI_COVERAGE',
  CLIRoot: 'XBELL_CLI_ROOT',
  CLI_PROJECTS: 'XBELL_CLI_PROJECTS',
  JSX_PRAGMA_FRAG: 'XBELL_JSX_PRAGMA_FRAG',
  JSX_PRAGMA: 'XBELL_JSX_PRAGMA',
  JSX_IMPORT_SOURCE: 'XBELL_JSX_IMPORT_SOURCE',
  JSX_RUNTIME: 'XBELL_JSX_RUNTIME',
} as const;
